# wordpress-app.yaml
apiVersion: argocd.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: '[https://wordpress-helm.github.io/charts/](https://wordpress-helm.github.io/charts/)' # The NEW, CORRECT Community chart repo
    targetRevision: 21.1.0 # A recent, stable chart version
    chart: wordpress
    helm:
      values: | # All our custom settings
        wordpressPassword: YourSecurePassword123
        mariadb:
          enabled: true
          rootPassword: YourMariaDBPassword123 # Note the variable name change
          image:
            registry: 192.168.81.130:30003
            repository: wordpress/mariadb # (Project/Image)
            tag: "11.4" # STABLE tag
        service:
          type: NodePort

        # --- THIS IS THE KEY PART ---
        # Tell Helm to pull images from our private Harbor registry
        image:
          registry: 192.168.81.130:30003
          repository: wordpress/wordpress # (Project/Image)
          tag: "6.6" # STABLE tag

  destination:
    server: '[https://kubernetes.default.svc](https://kubernetes.default.svc)'
    namespace: wordpress # Deploy the app in its own namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Tell Argo to create the 'wordpress' namespace